#
# rename this template file to experiment_config.yaml
#

ADC:
  drate: '7500'
  gain: 1x
  port: COM3
Cryo:
  channel:
  - 3
  - 4
  - 5
  enabled: false
  temp:
    manual: false
    start: 100.0
    step: 10.0
    stop: 400.0
Magnet:
  amplitude: 10.0
  frequency: 0.1
  n_ramps: 2
  pause_between_ramps: 0.5
  pause_time_at_zero: 0
  time: 0.2
  waveform: triangle
OLED:
  power_type: V
  prep_time: 0.0
  v: -0.003
Saving:
  filename: data.csv
  folder: ""
